from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities import Account, Candle, Symbol, Trade


class SymbolRepository(Protocol):
    async def list(self) -> list[Symbol]: ...
    async def get(self, symbol_id: UUID) -> Symbol | None: ...
    async def get_by_name(self, name: str) -> Symbol | None: ...
    async def add(self, symbol: Symbol) -> Symbol: ...
    async def update(self, symbol: Symbol) -> Symbol: ...
    async def delete(self, symbol_id: UUID) -> None: ...


class CandleRepository(Protocol):
    async def list(self, symbol_id: UUID | None = None, limit: int = 200) -> list[Candle]: ...
    async def add(self, candle: Candle) -> Candle: ...


class AccountRepository(Protocol):
    async def list(self) -> list[Account]: ...
    async def get(self, account_id: UUID) -> Account | None: ...
    async def get_by_external_id(self, external_id: str) -> Account | None: ...
    async def add(self, account: Account) -> Account: ...


class TradeRepository(Protocol):
    async def list(self, account_id: UUID | None = None, limit: int = 200) -> list[Trade]: ...
    async def add(self, trade: Trade) -> Trade: ...
